add specific permissions to Sensision directories

diff --git a/sensision/src/main/shell/sensision.init b/sensision/src/main/shell/sensision.init
--- a/sensision/src/main/shell/sensision.init
+++ b/sensision/src/main/shell/sensision.init
@@ -29,8 +29,38 @@ fi
 
 VERSION=@VERSION@
 
-SENSISION_HOME=/opt/sensision-${VERSION}
+OS=$(uname -s)
+
+#JAVA_HOME=/opt/java8
+
+if [ -z "$JAVA_HOME" ]; then
+  echo "JAVA_HOME not set";
+  exit 1
+fi
+
+#
+# WARP10 jar and config are required to generate Sensision tokens
+#
+#WARP10_JAR=
+#WARP10_CONF=
+
+#SENSISION_HOME=/opt/sensision-${VERSION}
+
+# If SENSISION_HOME is not defined, set it to the parent directory
+if [ -z "${SENSISION_HOME}" ]; then
+  if [ "Darwin" = "${OS}" ]
+  then
+    pushd $(dirname $0)/.. > /dev/null 2>&1
+    SENSISION_HOME=`pwd`
+    popd > /dev/null 2>&1
+  else
+    SENSISION_HOME=$(dirname $(readlink -f $0))/..
+  fi
+fi
+
 SENSISION_USER=sensision
+SENSISION_GROUP=sensision
+WARP10_GROUP=warp10
 SENSISION_CONFIG=${SENSISION_HOME}/etc/sensision.conf
 SENSISION_TOKENS=${SENSISION_HOME}/etc/sensision.tokens
 SENSISION_JAR=${SENSISION_HOME}/bin/sensision-${VERSION}.jar
@@ -49,41 +79,28 @@ if [ -z "${SENSISION_DATA_DIR}" ]; then
   SENSISION_DATA_DIR=${SENSISION_HOME}
 fi
 
-#
-# WARP10 jar is required to use Worf
-#
-#WARP10_JAR=
-#WARP10_CONF=
-
-#JAVA_HOME=/opt/java8
-
-if [ -z "$JAVA_HOME" ]; then
-  echo "JAVA_HOME not set";
-  exit 1
-fi
-
 initConfig() {
 
   echo "Init Sensision.."
 
-  # sensision user ?
-  if ! id -u "${SENSISION_USER}" >/dev/null 2>&1; then
-  echo "User '${SENSISION_USER}'' does not exist - Creating it.."
-    # Create user warp10
-    if [ "`which useradd`" = "" ]; then
-      if [ "`which adduser`" != "" ]; then
-        adduser -D -s -H -h ${SENSISION_HOME} -s /bin/bash ${SENSISION_USER}
-      else
-        echo "Hmmm that's embarassing but I do not know how to create the ${SENSISION_USER} user with home directory ${SENSISION_HOME}, could you do it for me and run the script again?"
-        exit 1
-      fi
-    else
-      useradd -d ${SENSISION_HOME} -M -r ${SENSISION_USER} -s /bin/bash
-    fi
-  fi
-
   # Fix ownership
-  chown -R ${SENSISION_USER}:${SENSISION_USER} ${SENSISION_HOME}
+  chown -R ${SENSISION_USER}:${SENSISION_GROUP} ${SENSISION_HOME}
+
+  # Fix permissions
+  echo "Fix permissions.."
+  # Everyone should have r+x permissions to SENSISION_HOME (targets, metrics)
+  chmod 755 ${SENSISION_HOME}
+  chmod 755 ${SENSISION_HOME}/bin
+  chmod 755 ${SENSISION_HOME}/etc
+  chmod 755 ${SENSISION_HOME}/templates
+  chmod 755 ${SENSISION_HOME}/logs
+  chmod 1733 ${SENSISION_HOME}/targets
+  chmod 1733 ${SENSISION_HOME}/metrics
+  chmod 700 ${SENSISION_HOME}/queued
+  chmod -R 755 ${SENSISION_HOME}/scripts
+  chmod 644 ${SENSISION_JAR}
+  chmod 755 ${SENSISION_HOME}/bin/sensision.init
+  chmod 4750 ${SENSISION_HOME}/bin/procDump
 
   #
   # ${SENSISION_HOME} != ${SENSISION_DATA_DIR}
@@ -106,8 +123,18 @@ initConfig() {
     fi
 
     # force ownerships / permissions
-    chown ${SENSISION_USER}:${SENSISION_USER} ${SENSISION_DATA_DIR}
-    chmod 750 ${SENSISION_DATA_DIR}
+    chown ${SENSISION_USER}:${SENSISION_GROUP} ${SENSISION_DATA_DIR}
+    # Everyone should have r+x permissions to SENSISION_DATA_DIR (targets, metrics)
+    chmod 755 ${SENSISION_DATA_DIR}
+
+    #
+    # Test access to SENSISION_DATA_DIR and its parent directories
+    #
+    su ${SENSISION_USER} -c "ls ${SENSISION_DATA_DIR} 2>&1"
+    if [ $? != 0 ]; then
+      echo "ERROR: Cannot access to ${SENSISION_DATA_DIR}"
+      exit 1
+    fi
 
     # Move etc dir to ${SENSISION_DATA_DIR}
     if [ -e ${SENSISION_DATA_DIR}/logs ]; then
@@ -120,7 +147,7 @@ initConfig() {
       exit 1
     fi
     ln -s ${SENSISION_DATA_DIR}/etc ${SENSISION_HOME}/etc
-    chown ${SENSISION_USER}:${SENSISION_USER} ${SENSISION_DATA_DIR}/etc
+    chown ${SENSISION_USER}:${SENSISION_GROUP} ${SENSISION_DATA_DIR}/etc
     chmod 755 ${SENSISION_DATA_DIR}/etc
 
     # Move logs dir to ${SENSISION_DATA_DIR}
@@ -134,7 +161,7 @@ initConfig() {
       exit 1
     fi
     ln -s ${SENSISION_DATA_DIR}/logs ${SENSISION_HOME}/logs
-    chown ${SENSISION_USER}:${SENSISION_USER} ${SENSISION_DATA_DIR}/logs
+    chown ${SENSISION_USER}:${SENSISION_GROUP} ${SENSISION_DATA_DIR}/logs
     chmod 755 ${SENSISION_DATA_DIR}/logs
 
     # Move scripts dir to ${SENSISION_DATA_DIR}
@@ -148,7 +175,7 @@ initConfig() {
       exit 1
     fi
     ln -s ${SENSISION_DATA_DIR}/scripts ${SENSISION_HOME}/scripts
-    chown -R ${SENSISION_USER}:${SENSISION_USER} ${SENSISION_DATA_DIR}/scripts
+    chown -R ${SENSISION_USER}:${SENSISION_GROUP} ${SENSISION_DATA_DIR}/scripts
     chmod 775 ${SENSISION_DATA_DIR}/scripts
 
     # Move metrics dir to ${SENSISION_DATA_DIR}
@@ -162,7 +189,7 @@ initConfig() {
       exit 1
     fi
     ln -s ${SENSISION_DATA_DIR}/metrics ${SENSISION_HOME}/metrics
-    chown ${SENSISION_USER}:${SENSISION_USER} ${SENSISION_DATA_DIR}/metrics
+    chown ${SENSISION_USER}:${SENSISION_GROUP} ${SENSISION_DATA_DIR}/metrics
     chmod 1733 ${SENSISION_DATA_DIR}/metrics
 
     # Move targets dir to ${SENSISION_DATA_DIR}
@@ -176,7 +203,7 @@ initConfig() {
       exit 1
     fi
     ln -s ${SENSISION_DATA_DIR}/targets ${SENSISION_HOME}/targets
-    chown ${SENSISION_USER}:${SENSISION_USER} ${SENSISION_DATA_DIR}/targets
+    chown ${SENSISION_USER}:${SENSISION_GROUP} ${SENSISION_DATA_DIR}/targets
     chmod 1733 ${SENSISION_DATA_DIR}/targets
 
     # Move queued dir to ${SENSISION_DATA_DIR}
@@ -190,28 +217,17 @@ initConfig() {
       exit 1
     fi
     ln -s ${SENSISION_DATA_DIR}/queued ${SENSISION_HOME}/queued
-    chown ${SENSISION_USER}:${SENSISION_USER} ${SENSISION_DATA_DIR}/queued
+    chown ${SENSISION_USER}:${SENSISION_GROUP} ${SENSISION_DATA_DIR}/queued
     chmod 700 ${SENSISION_DATA_DIR}/queued
 
   fi
 
-  # /var/run/sensision..
+  # check /var/run/sensision does not exist during init..
   if [ -e /var/run/sensision ]; then
     echo "ERROR: /var/run/sensision already exists - Delete it before."
     exit 1
   fi
 
-  mkdir /var/run/sensision
-  if [ $? != 0 ]; then
-    echo "ERROR: Cannot create /var/run/sensision"
-    exit 1
-  fi
-
-  chown -R ${SENSISION_USER}:${SENSISION_USER} /var/run/sensision
-  chmod 755 /var/run/sensision
-  ln -s ${SENSISION_DATA_DIR}/metrics /var/run/sensision/metrics
-  ln -s ${SENSISION_DATA_DIR}/targets /var/run/sensision/targets
-  ln -s ${SENSISION_DATA_DIR}/queued /var/run/sensision/queued
   if [ -e /etc/init.d/sensision ]; then
     echo "/etc/init.d/sensision already exists - Delete it.."
     rm /etc/init.d/sensision
@@ -223,15 +239,16 @@ initConfig() {
 
   if [ "${WARP10_CONF}" != "" ]; then
     if [ -f ${WARP10_CONF} ]; then
+      echo "Sensision: generate configuration with Warp10 conf/jar.."
       echo "WARP10_CONF: ${WARP10_CONF}"
-      #su ${SENSISION_USER} -c "${JAVA_HOME}/bin/java -cp ${WARP10_JAR} io.warp10.worf.Worf -a io.warp10.sensision -ks ${WARP10_CONF} -puidg -t -ttl 3153600000000 ${SENSISION_HOME}/templates/sensision.template -o ${SENSISION_CONFIG}"
+      echo "WARP10_JAR: ${WARP10_JAR}"
       su ${SENSISION_USER} -c "${JAVA_HOME}/bin/java -cp ${WARP10_JAR} io.warp10.worf.Worf -q -a io.warp10.sensision -puidg -t -ttl 3153600000000 ${WARP10_CONF}" > ${SENSISION_TOKENS}
       # Slr I trust you...
       TOKEN_TYPE="write"
       WRITE_TOKEN="$(cat ${SENSISION_TOKENS} | sed 's/\\\\\//\//g' | sed 's/[{}]//g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | sed 's/\"\:\"/\|/g' | sed 's/[\,]/ /g' | sed 's/\"//g' | grep -w "${TOKEN_TYPE}" | cut -d'|' -f 3 | tr -d '\n\r')"
       cp ${SENSISION_HOME}/templates/sensision.template ${SENSISION_CONFIG}
       sed -i 's/@warp:WriteToken@/'"${WRITE_TOKEN}"'/' ${SENSISION_CONFIG}
-      chown ${SENSISION_USER}:${SENSISION_USER} ${SENSISION_CONFIG}
+      chown ${SENSISION_USER}:${SENSISION_GROUP} ${SENSISION_CONFIG}
       chmod 664 ${SENSISION_CONFIG}
     else
       echo "ERROR: '${WARP10_CONF}' does not exist. Skip generation of Sensision configuration."
@@ -240,7 +257,7 @@ initConfig() {
   else 
     echo "'WARP10_CONF' is not defined. Skip generation of Sensision configuration - Copy template as it is"
     cp ${SENSISION_HOME}/templates/sensision.template ${SENSISION_CONFIG}
-    chown ${SENSISION_USER}:${SENSISION_USER} ${SENSISION_CONFIG}
+    chown ${SENSISION_USER}:${SENSISION_GROUP} ${SENSISION_CONFIG}
     chmod 664 ${SENSISION_CONFIG}
     echo "Starting is going to be stopped - Update configuration '${SENSISION_CONFIG}' manually and restart Sensision"
     exit 2
@@ -248,6 +265,23 @@ initConfig() {
 }
 
 start() {
+  # sensision user ?
+  if ! id -u "${SENSISION_USER}" >/dev/null 2>&1; then
+  echo "User '${SENSISION_USER}'' does not exist - Creating it.."
+    # Create user sensision and add it to warp10 group
+    if [ "`which useradd`" = "" ]; then
+      if [ "`which adduser`" != "" ]; then
+        adduser -D -s -H -h ${SENSISION_HOME} -s /bin/bash ${SENSISION_USER}
+        addgroup ${SENSISION_USER} ${WARP10_GROUP}
+      else
+        echo "Hmmm that's embarassing but I do not know how to create the ${SENSISION_USER} user with home directory ${SENSISION_HOME}, could you do it for me and run the script again?"
+        exit 1
+      fi
+    else
+      useradd -d ${SENSISION_HOME} -M -r ${SENSISION_USER} -G ${WARP10_GROUP} -s /bin/bash
+    fi
+  fi
+
   #
   # Config file exists ?
   #
@@ -255,6 +289,25 @@ start() {
     echo "Config file does not exist - Creating it from template..."
     initConfig
   fi
+
+  # /var/run/sensision may have been deleted after reboot
+  if [ ! -e /var/run/sensision ]; then
+    echo "Create /var/run/sensision.."
+    mkdir /var/run/sensision
+    if [ $? != 0 ]; then
+      echo "ERROR: Cannot create /var/run/sensision"
+      exit 1
+    fi
+    chown -R ${SENSISION_USER}:${SENSISION_GROUP} /var/run/sensision
+    chmod 755 /var/run/sensision
+    ln -s ${SENSISION_DATA_DIR}/metrics /var/run/sensision/metrics
+    ln -s ${SENSISION_DATA_DIR}/targets /var/run/sensision/targets
+    ln -s ${SENSISION_DATA_DIR}/queued /var/run/sensision/queued
+  fi
+  
+  #
+  # Start..
+  #
   su "${SENSISION_USER}" -c "${JAVA_HOME}/bin/java -Xmx${SENSISION_HEAP} ${SENSISION_OPTS} -Dsensision.config=${SENSISION_CONFIG} -cp ${SENSISION_CP} ${SENSISION_CLASS} >> ${SENSISION_HOME}/logs/nohup.out 2>&1 &"
 }
 
